# Generated by Django 3.0.5 on 2020-04-11 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollment',
            name='course_num',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='dept_code',
        ),
        migrations.AddField(
            model_name='enrollment',
            name='course_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='students.Course'),
            preserve_default=False,
        ),
    ]
